SOURCE:=$(wildcard laba?.tex)
NAME:=$(subst .tex,,$(SOURCE))
TESTSTR:= 'Label(s) may have changed'

.PHONY: force clean

$(NAME).pdf: $(SOURCE) content.tex ../appendix/lsm.tex
	@pdflatex $< && (grep -q $(TESTSTR) $(NAME).log && pdflatex $< || true)

force: 
	@pdflatex $(SOURCE) && \
	(grep -q $(TESTSTR) $(NAME).log && pdflatex $(SOURCE) || true)

clean:
	@echo "Cleaning PDF and LaTeX temporary files"
	@rm -f $(NAME).pdf $(NAME).log $(NAME).out $(NAME).aux
	
